version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/github_action
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/gh_action.sh
      timeout: 60
      runas: ubuntu